import hljs from './core.mjs';
import ayaml from './languages/yaml.mjs';
import axml from './languages/xml.mjs';
import awasm from './languages/wasm.mjs';
import avbnet from './languages/vbnet.mjs';
import atypescript from './languages/typescript.mjs';
import aswift from './languages/swift.mjs';
import asql from './languages/sql.mjs';
import ashell from './languages/shell.mjs';
import ascss from './languages/scss.mjs';
import arust from './languages/rust.mjs';
import aruby from './languages/ruby.mjs';
import ar from './languages/r.mjs';
import apython from './languages/python.mjs';
import apython_repl from './languages/python-repl.mjs';
import aplaintext from './languages/plaintext.mjs';
import aphp from './languages/php.mjs';
import aphp_template from './languages/php-template.mjs';
import aperl from './languages/perl.mjs';
import aobjectivec from './languages/objectivec.mjs';
import amarkdown from './languages/markdown.mjs';
import amakefile from './languages/makefile.mjs';
import alua from './languages/lua.mjs';
import aless from './languages/less.mjs';
import akotlin from './languages/kotlin.mjs';
import ajson from './languages/json.mjs';
import ajavascript from './languages/javascript.mjs';
import ajava from './languages/java.mjs';
import aini from './languages/ini.mjs';
import agraphql from './languages/graphql.mjs';
import ago from './languages/go.mjs';
import adiff from './languages/diff.mjs';
import acss from './languages/css.mjs';
import acsharp from './languages/csharp.mjs';
import acpp from './languages/cpp.mjs';
import ac from './languages/c.mjs';
import abash from './languages/bash.mjs';

hljs.registerLanguage('yaml', ayaml);
hljs.registerLanguage('xml', axml);
hljs.registerLanguage('wasm', awasm);
hljs.registerLanguage('vbnet', avbnet);
hljs.registerLanguage('typescript', atypescript);
hljs.registerLanguage('swift', aswift);
hljs.registerLanguage('sql', asql);
hljs.registerLanguage('shell', ashell);
hljs.registerLanguage('scss', ascss);
hljs.registerLanguage('rust', arust);
hljs.registerLanguage('ruby', aruby);
hljs.registerLanguage('r', ar);
hljs.registerLanguage('python', apython);
hljs.registerLanguage('python-repl', apython_repl);
hljs.registerLanguage('plaintext', aplaintext);
hljs.registerLanguage('php', aphp);
hljs.registerLanguage('php-template', aphp_template);
hljs.registerLanguage('perl', aperl);
hljs.registerLanguage('objectivec', aobjectivec);
hljs.registerLanguage('markdown', amarkdown);
hljs.registerLanguage('makefile', amakefile);
hljs.registerLanguage('lua', alua);
hljs.registerLanguage('less', aless);
hljs.registerLanguage('kotlin', akotlin);
hljs.registerLanguage('json', ajson);
hljs.registerLanguage('javascript', ajavascript);
hljs.registerLanguage('java', ajava);
hljs.registerLanguage('ini', aini);
hljs.registerLanguage('graphql', agraphql);
hljs.registerLanguage('go', ago);
hljs.registerLanguage('diff', adiff);
hljs.registerLanguage('css', acss);
hljs.registerLanguage('csharp', acsharp);
hljs.registerLanguage('cpp', acpp);
hljs.registerLanguage('c', ac);
hljs.registerLanguage('bash', abash);

hljs.HighlightJS = hljs;
export default hljs;
