import hljs from './core.mjs';
import azephir from './languages/zephir.mjs';
import ayaml from './languages/yaml.mjs';
import axquery from './languages/xquery.mjs';
import axml from './languages/xml.mjs';
import axl from './languages/xl.mjs';
import ax86asm from './languages/x86asm.mjs';
import awren from './languages/wren.mjs';
import awasm from './languages/wasm.mjs';
import avim from './languages/vim.mjs';
import avhdl from './languages/vhdl.mjs';
import averilog from './languages/verilog.mjs';
import avbscript from './languages/vbscript.mjs';
import avbscript_html from './languages/vbscript-html.mjs';
import avbnet from './languages/vbnet.mjs';
import avala from './languages/vala.mjs';
import atypescript from './languages/typescript.mjs';
import atwig from './languages/twig.mjs';
import atp from './languages/tp.mjs';
import athrift from './languages/thrift.mjs';
import atcl from './languages/tcl.mjs';
import atap from './languages/tap.mjs';
import ataggerscript from './languages/taggerscript.mjs';
import aswift from './languages/swift.mjs';
import asubunit from './languages/subunit.mjs';
import astylus from './languages/stylus.mjs';
import astep21 from './languages/step21.mjs';
import astata from './languages/stata.mjs';
import astan from './languages/stan.mjs';
import asql from './languages/sql.mjs';
import asqf from './languages/sqf.mjs';
import asml from './languages/sml.mjs';
import asmalltalk from './languages/smalltalk.mjs';
import asmali from './languages/smali.mjs';
import ashell from './languages/shell.mjs';
import ascss from './languages/scss.mjs';
import ascilab from './languages/scilab.mjs';
import ascheme from './languages/scheme.mjs';
import ascala from './languages/scala.mjs';
import asas from './languages/sas.mjs';
import arust from './languages/rust.mjs';
import aruleslanguage from './languages/ruleslanguage.mjs';
import aruby from './languages/ruby.mjs';
import arsl from './languages/rsl.mjs';
import arouteros from './languages/routeros.mjs';
import aroboconf from './languages/roboconf.mjs';
import arib from './languages/rib.mjs';
import areasonml from './languages/reasonml.mjs';
import ar from './languages/r.mjs';
import aqml from './languages/qml.mjs';
import aq from './languages/q.mjs';
import apython from './languages/python.mjs';
import apython_repl from './languages/python-repl.mjs';
import apurebasic from './languages/purebasic.mjs';
import apuppet from './languages/puppet.mjs';
import aprotobuf from './languages/protobuf.mjs';
import aproperties from './languages/properties.mjs';
import aprolog from './languages/prolog.mjs';
import aprofile from './languages/profile.mjs';
import aprocessing from './languages/processing.mjs';
import apowershell from './languages/powershell.mjs';
import apony from './languages/pony.mjs';
import aplaintext from './languages/plaintext.mjs';
import aphp from './languages/php.mjs';
import aphp_template from './languages/php-template.mjs';
import apgsql from './languages/pgsql.mjs';
import apf from './languages/pf.mjs';
import aperl from './languages/perl.mjs';
import aparser3 from './languages/parser3.mjs';
import aoxygene from './languages/oxygene.mjs';
import aopenscad from './languages/openscad.mjs';
import aocaml from './languages/ocaml.mjs';
import aobjectivec from './languages/objectivec.mjs';
import ansis from './languages/nsis.mjs';
import anode_repl from './languages/node-repl.mjs';
import anix from './languages/nix.mjs';
import anim from './languages/nim.mjs';
import anginx from './languages/nginx.mjs';
import anestedtext from './languages/nestedtext.mjs';
import an1ql from './languages/n1ql.mjs';
import amoonscript from './languages/moonscript.mjs';
import amonkey from './languages/monkey.mjs';
import amojolicious from './languages/mojolicious.mjs';
import amizar from './languages/mizar.mjs';
import amipsasm from './languages/mipsasm.mjs';
import amercury from './languages/mercury.mjs';
import amel from './languages/mel.mjs';
import amaxima from './languages/maxima.mjs';
import amatlab from './languages/matlab.mjs';
import amathematica from './languages/mathematica.mjs';
import amarkdown from './languages/markdown.mjs';
import amakefile from './languages/makefile.mjs';
import alua from './languages/lua.mjs';
import alsl from './languages/lsl.mjs';
import allvm from './languages/llvm.mjs';
import alivescript from './languages/livescript.mjs';
import alivecodeserver from './languages/livecodeserver.mjs';
import alisp from './languages/lisp.mjs';
import aless from './languages/less.mjs';
import aleaf from './languages/leaf.mjs';
import aldif from './languages/ldif.mjs';
import alatex from './languages/latex.mjs';
import alasso from './languages/lasso.mjs';
import akotlin from './languages/kotlin.mjs';
import ajulia from './languages/julia.mjs';
import ajulia_repl from './languages/julia-repl.mjs';
import ajson from './languages/json.mjs';
import ajboss_cli from './languages/jboss-cli.mjs';
import ajavascript from './languages/javascript.mjs';
import ajava from './languages/java.mjs';
import aisbl from './languages/isbl.mjs';
import airpf90 from './languages/irpf90.mjs';
import aini from './languages/ini.mjs';
import ainform7 from './languages/inform7.mjs';
import ahy from './languages/hy.mjs';
import ahttp from './languages/http.mjs';
import ahsp from './languages/hsp.mjs';
import ahaxe from './languages/haxe.mjs';
import ahaskell from './languages/haskell.mjs';
import ahandlebars from './languages/handlebars.mjs';
import ahaml from './languages/haml.mjs';
import agroovy from './languages/groovy.mjs';
import agraphql from './languages/graphql.mjs';
import agradle from './languages/gradle.mjs';
import agolo from './languages/golo.mjs';
import ago from './languages/go.mjs';
import agml from './languages/gml.mjs';
import aglsl from './languages/glsl.mjs';
import agherkin from './languages/gherkin.mjs';
import agcode from './languages/gcode.mjs';
import agauss from './languages/gauss.mjs';
import agams from './languages/gams.mjs';
import afsharp from './languages/fsharp.mjs';
import afortran from './languages/fortran.mjs';
import aflix from './languages/flix.mjs';
import afix from './languages/fix.mjs';
import aexcel from './languages/excel.mjs';
import aerlang from './languages/erlang.mjs';
import aerlang_repl from './languages/erlang-repl.mjs';
import aerb from './languages/erb.mjs';
import aelm from './languages/elm.mjs';
import aelixir from './languages/elixir.mjs';
import aebnf from './languages/ebnf.mjs';
import adust from './languages/dust.mjs';
import adts from './languages/dts.mjs';
import adsconfig from './languages/dsconfig.mjs';
import ados from './languages/dos.mjs';
import adockerfile from './languages/dockerfile.mjs';
import adns from './languages/dns.mjs';
import adjango from './languages/django.mjs';
import adiff from './languages/diff.mjs';
import adelphi from './languages/delphi.mjs';
import adart from './languages/dart.mjs';
import ad from './languages/d.mjs';
import acss from './languages/css.mjs';
import acsp from './languages/csp.mjs';
import acsharp from './languages/csharp.mjs';
import acrystal from './languages/crystal.mjs';
import acrmsh from './languages/crmsh.mjs';
import acpp from './languages/cpp.mjs';
import acos from './languages/cos.mjs';
import acoq from './languages/coq.mjs';
import acoffeescript from './languages/coffeescript.mjs';
import acmake from './languages/cmake.mjs';
import aclojure from './languages/clojure.mjs';
import aclojure_repl from './languages/clojure-repl.mjs';
import aclean from './languages/clean.mjs';
import aceylon from './languages/ceylon.mjs';
import acapnproto from './languages/capnproto.mjs';
import acal from './languages/cal.mjs';
import ac from './languages/c.mjs';
import abrainfuck from './languages/brainfuck.mjs';
import abnf from './languages/bnf.mjs';
import abasic from './languages/basic.mjs';
import abash from './languages/bash.mjs';
import aaxapta from './languages/axapta.mjs';
import aawk from './languages/awk.mjs';
import aavrasm from './languages/avrasm.mjs';
import aautoit from './languages/autoit.mjs';
import aautohotkey from './languages/autohotkey.mjs';
import aaspectj from './languages/aspectj.mjs';
import aasciidoc from './languages/asciidoc.mjs';
import aarmasm from './languages/armasm.mjs';
import aarduino from './languages/arduino.mjs';
import aarcade from './languages/arcade.mjs';
import aapplescript from './languages/applescript.mjs';
import aapache from './languages/apache.mjs';
import aangelscript from './languages/angelscript.mjs';
import aada from './languages/ada.mjs';
import aactionscript from './languages/actionscript.mjs';
import aaccesslog from './languages/accesslog.mjs';
import aabnf from './languages/abnf.mjs';
import a1c from './languages/1c.mjs';

hljs.registerLanguage('zephir', azephir);
hljs.registerLanguage('yaml', ayaml);
hljs.registerLanguage('xquery', axquery);
hljs.registerLanguage('xml', axml);
hljs.registerLanguage('xl', axl);
hljs.registerLanguage('x86asm', ax86asm);
hljs.registerLanguage('wren', awren);
hljs.registerLanguage('wasm', awasm);
hljs.registerLanguage('vim', avim);
hljs.registerLanguage('vhdl', avhdl);
hljs.registerLanguage('verilog', averilog);
hljs.registerLanguage('vbscript', avbscript);
hljs.registerLanguage('vbscript-html', avbscript_html);
hljs.registerLanguage('vbnet', avbnet);
hljs.registerLanguage('vala', avala);
hljs.registerLanguage('typescript', atypescript);
hljs.registerLanguage('twig', atwig);
hljs.registerLanguage('tp', atp);
hljs.registerLanguage('thrift', athrift);
hljs.registerLanguage('tcl', atcl);
hljs.registerLanguage('tap', atap);
hljs.registerLanguage('taggerscript', ataggerscript);
hljs.registerLanguage('swift', aswift);
hljs.registerLanguage('subunit', asubunit);
hljs.registerLanguage('stylus', astylus);
hljs.registerLanguage('step21', astep21);
hljs.registerLanguage('stata', astata);
hljs.registerLanguage('stan', astan);
hljs.registerLanguage('sql', asql);
hljs.registerLanguage('sqf', asqf);
hljs.registerLanguage('sml', asml);
hljs.registerLanguage('smalltalk', asmalltalk);
hljs.registerLanguage('smali', asmali);
hljs.registerLanguage('shell', ashell);
hljs.registerLanguage('scss', ascss);
hljs.registerLanguage('scilab', ascilab);
hljs.registerLanguage('scheme', ascheme);
hljs.registerLanguage('scala', ascala);
hljs.registerLanguage('sas', asas);
hljs.registerLanguage('rust', arust);
hljs.registerLanguage('ruleslanguage', aruleslanguage);
hljs.registerLanguage('ruby', aruby);
hljs.registerLanguage('rsl', arsl);
hljs.registerLanguage('routeros', arouteros);
hljs.registerLanguage('roboconf', aroboconf);
hljs.registerLanguage('rib', arib);
hljs.registerLanguage('reasonml', areasonml);
hljs.registerLanguage('r', ar);
hljs.registerLanguage('qml', aqml);
hljs.registerLanguage('q', aq);
hljs.registerLanguage('python', apython);
hljs.registerLanguage('python-repl', apython_repl);
hljs.registerLanguage('purebasic', apurebasic);
hljs.registerLanguage('puppet', apuppet);
hljs.registerLanguage('protobuf', aprotobuf);
hljs.registerLanguage('properties', aproperties);
hljs.registerLanguage('prolog', aprolog);
hljs.registerLanguage('profile', aprofile);
hljs.registerLanguage('processing', aprocessing);
hljs.registerLanguage('powershell', apowershell);
hljs.registerLanguage('pony', apony);
hljs.registerLanguage('plaintext', aplaintext);
hljs.registerLanguage('php', aphp);
hljs.registerLanguage('php-template', aphp_template);
hljs.registerLanguage('pgsql', apgsql);
hljs.registerLanguage('pf', apf);
hljs.registerLanguage('perl', aperl);
hljs.registerLanguage('parser3', aparser3);
hljs.registerLanguage('oxygene', aoxygene);
hljs.registerLanguage('openscad', aopenscad);
hljs.registerLanguage('ocaml', aocaml);
hljs.registerLanguage('objectivec', aobjectivec);
hljs.registerLanguage('nsis', ansis);
hljs.registerLanguage('node-repl', anode_repl);
hljs.registerLanguage('nix', anix);
hljs.registerLanguage('nim', anim);
hljs.registerLanguage('nginx', anginx);
hljs.registerLanguage('nestedtext', anestedtext);
hljs.registerLanguage('n1ql', an1ql);
hljs.registerLanguage('moonscript', amoonscript);
hljs.registerLanguage('monkey', amonkey);
hljs.registerLanguage('mojolicious', amojolicious);
hljs.registerLanguage('mizar', amizar);
hljs.registerLanguage('mipsasm', amipsasm);
hljs.registerLanguage('mercury', amercury);
hljs.registerLanguage('mel', amel);
hljs.registerLanguage('maxima', amaxima);
hljs.registerLanguage('matlab', amatlab);
hljs.registerLanguage('mathematica', amathematica);
hljs.registerLanguage('markdown', amarkdown);
hljs.registerLanguage('makefile', amakefile);
hljs.registerLanguage('lua', alua);
hljs.registerLanguage('lsl', alsl);
hljs.registerLanguage('llvm', allvm);
hljs.registerLanguage('livescript', alivescript);
hljs.registerLanguage('livecodeserver', alivecodeserver);
hljs.registerLanguage('lisp', alisp);
hljs.registerLanguage('less', aless);
hljs.registerLanguage('leaf', aleaf);
hljs.registerLanguage('ldif', aldif);
hljs.registerLanguage('latex', alatex);
hljs.registerLanguage('lasso', alasso);
hljs.registerLanguage('kotlin', akotlin);
hljs.registerLanguage('julia', ajulia);
hljs.registerLanguage('julia-repl', ajulia_repl);
hljs.registerLanguage('json', ajson);
hljs.registerLanguage('jboss-cli', ajboss_cli);
hljs.registerLanguage('javascript', ajavascript);
hljs.registerLanguage('java', ajava);
hljs.registerLanguage('isbl', aisbl);
hljs.registerLanguage('irpf90', airpf90);
hljs.registerLanguage('ini', aini);
hljs.registerLanguage('inform7', ainform7);
hljs.registerLanguage('hy', ahy);
hljs.registerLanguage('http', ahttp);
hljs.registerLanguage('hsp', ahsp);
hljs.registerLanguage('haxe', ahaxe);
hljs.registerLanguage('haskell', ahaskell);
hljs.registerLanguage('handlebars', ahandlebars);
hljs.registerLanguage('haml', ahaml);
hljs.registerLanguage('groovy', agroovy);
hljs.registerLanguage('graphql', agraphql);
hljs.registerLanguage('gradle', agradle);
hljs.registerLanguage('golo', agolo);
hljs.registerLanguage('go', ago);
hljs.registerLanguage('gml', agml);
hljs.registerLanguage('glsl', aglsl);
hljs.registerLanguage('gherkin', agherkin);
hljs.registerLanguage('gcode', agcode);
hljs.registerLanguage('gauss', agauss);
hljs.registerLanguage('gams', agams);
hljs.registerLanguage('fsharp', afsharp);
hljs.registerLanguage('fortran', afortran);
hljs.registerLanguage('flix', aflix);
hljs.registerLanguage('fix', afix);
hljs.registerLanguage('excel', aexcel);
hljs.registerLanguage('erlang', aerlang);
hljs.registerLanguage('erlang-repl', aerlang_repl);
hljs.registerLanguage('erb', aerb);
hljs.registerLanguage('elm', aelm);
hljs.registerLanguage('elixir', aelixir);
hljs.registerLanguage('ebnf', aebnf);
hljs.registerLanguage('dust', adust);
hljs.registerLanguage('dts', adts);
hljs.registerLanguage('dsconfig', adsconfig);
hljs.registerLanguage('dos', ados);
hljs.registerLanguage('dockerfile', adockerfile);
hljs.registerLanguage('dns', adns);
hljs.registerLanguage('django', adjango);
hljs.registerLanguage('diff', adiff);
hljs.registerLanguage('delphi', adelphi);
hljs.registerLanguage('dart', adart);
hljs.registerLanguage('d', ad);
hljs.registerLanguage('css', acss);
hljs.registerLanguage('csp', acsp);
hljs.registerLanguage('csharp', acsharp);
hljs.registerLanguage('crystal', acrystal);
hljs.registerLanguage('crmsh', acrmsh);
hljs.registerLanguage('cpp', acpp);
hljs.registerLanguage('cos', acos);
hljs.registerLanguage('coq', acoq);
hljs.registerLanguage('coffeescript', acoffeescript);
hljs.registerLanguage('cmake', acmake);
hljs.registerLanguage('clojure', aclojure);
hljs.registerLanguage('clojure-repl', aclojure_repl);
hljs.registerLanguage('clean', aclean);
hljs.registerLanguage('ceylon', aceylon);
hljs.registerLanguage('capnproto', acapnproto);
hljs.registerLanguage('cal', acal);
hljs.registerLanguage('c', ac);
hljs.registerLanguage('brainfuck', abrainfuck);
hljs.registerLanguage('bnf', abnf);
hljs.registerLanguage('basic', abasic);
hljs.registerLanguage('bash', abash);
hljs.registerLanguage('axapta', aaxapta);
hljs.registerLanguage('awk', aawk);
hljs.registerLanguage('avrasm', aavrasm);
hljs.registerLanguage('autoit', aautoit);
hljs.registerLanguage('autohotkey', aautohotkey);
hljs.registerLanguage('aspectj', aaspectj);
hljs.registerLanguage('asciidoc', aasciidoc);
hljs.registerLanguage('armasm', aarmasm);
hljs.registerLanguage('arduino', aarduino);
hljs.registerLanguage('arcade', aarcade);
hljs.registerLanguage('applescript', aapplescript);
hljs.registerLanguage('apache', aapache);
hljs.registerLanguage('angelscript', aangelscript);
hljs.registerLanguage('ada', aada);
hljs.registerLanguage('actionscript', aactionscript);
hljs.registerLanguage('accesslog', aaccesslog);
hljs.registerLanguage('abnf', aabnf);
hljs.registerLanguage('1c', a1c);

hljs.HighlightJS = hljs;
export default hljs;
